application: qwiznation
version: 1
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: webapp2
  version: 2.5.2
- name: jinja2
  version: 2.6
- name: pycrypto
  version: 2.6

handlers:
- url: /assets
  static_dir: assets

- url: /.*
  script: qwiznation.app
